In [9]:
## I/O with numpy
## As part of programming requirements we need to store data permanently for futuer purposes
## Files are a  very common permanent area to store out data
## Types of files 1) Binary files- Used to store binary data like images video files audio files etc
## 2) Text files-Used to store character data (.txt and .csv)
## To store and retrieve of numpy array in binary format save() and load() are used it stores with extension .npy
## Example below
import numpy as np
a= np.arange(0,100,10)
print(a)
np.save('kariuki',a)
print(a)

import numpy as np 
b= np.load('kariuki.npy')
print(b)
 

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]


In [16]:
## storage abd retrieve of data in text file we use savetxt()and loadtxt() functions

a=np.arange(1,20)
a
np.savetxt ('hum.txt',a)

b=np.loadtxt('hum.txt')
print(b)
print(type(b))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19.]
<class 'numpy.ndarray'>


In [21]:
## To store and retrieve data in csv file format is done wit savetxt() and load() with delimiter parameters
b
np.savetxt('jecinta.csv',b,delimiter=',')

c=np.loadtxt('jecinta.csv')
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

In [48]:
## Binary files
## create a 1D array
## Remember to load the file you have to use .npy extension
d=np.array([11,12,13,14,15])
d
np.save('njeri',d)
e=np.load('njeri.npy')
type (e)
## Remember always to save in a csv file you have to always pass the delimiter=,
e=np.array([11,12,13,24,25,26])
np.savetxt('wanjiku.csv',e,delimiter=',')
f=np.loadtxt("wanjiku.csv")
print(type(f))


<class 'numpy.ndarray'>


In [70]:
## sprinting line into columns
##genfromtxt runs two main loops. 
## The first loop converts each line of the file in a sequence of strings. 
##The second loop converts each string to the appropriate data type
from io import StringIO
hum=u"1, 2, 3\n4, 5, 6"
print(type(hum))
hum
np.genfromtxt(StringIO(hum),delimiter=",")

<class 'str'>


array([[1., 2., 3.],
       [4., 5., 6.]])

In [62]:
>>> data = u"""#
... # Skip me !
... # Skip me too !
... 1, 2
... 3, 4
... 5, 6 #This is the third line of the data
... 7, 8
... # And here comes the last line
... 9, 0
... """
>>> np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [ ]:
# from io import StringIO
data=u"\n".join(str(i) for i in range(10))
print(type(data))
data
## output will be like this'0\n1\n2\n3\n4\n5\n6\n7\n8\n9'
np.genfromtxt(StringIO(data),)/
\





# from io import StringIO
data=u"\n".join(str(i) for i in range(10))
print(type(data))
data
## output will be like this'0\n1\n2\n3\n4\n5\n6\n7\n8\n9'
np.genfromtxt(StringIO(data),)/
\





In [1]:
print("hum")

hum


In [22]:
hum = u"\n".join(str(i)for i in range(10))
print(hum)

kariuki=u"\n".join(str(i) for i in range(10))
print(kariuki)
import numpy as np
x=np.arange(10)
print(x)

0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
[0 1 2 3 4 5 6 7 8 9]


In [32]:
import numpy as np
y=np.arange (10)
print(y)
print(y[1])


[0 1 2 3 4 5 6 7 8 9]
1


In [ ]:
## Array Broadcasting eg x+y of two different arrays
## Array broadcasting is a way of doing elementwice operations on arrays of different shapes
x.shape==(2,3) ## 2 by 3 matrix


y.shape==(2,3)## compatible since they are of the same shape with x
y.shape==(2,1)## the twos match and one can match with anything thus they are compatible
y.shape==(1,3)## one can match with two and 3 can match with 3
y.shape==(3,)## This case you imagine that it looks like this one (1,3) thus one can match with 2 and 3 can match with 3
 ## Results in (2,3) shape
    
    
y.shape==(3,2) ## 3 does not match with 2 and 2 does not match with3
y.shape==(2,) ## It looks like this (1,2) thus not compatible because 1 match with 2 and buy 2 does not match with 3


x.shape==(1,2,3,5,1,11,1,17)
y.shape=        (1,7,1,1,17) #compatible
## result shape is (1,2,3,5,7,11,1,17)




In [49]:
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(x)
y=np.array([[0,1,2],[3,4,5]])
print(y)
b=np.array([1,10,100])
print(b)
print(y+b)
print(x+b)
c=np.array([1,10,100]).reshape(3,1)
print(c)
##print(y+c)## This will results into an error since operator cannot broadcast (2,3) and (3,1)
print(b+b)
# x=(3,3)
# c=(3,1)
shape = (3,3)
out=np.empty(shape,dtype=int)
N0,N1=shape
for i in range(N0):
    for j in range(N1):
        out[i,j]=x[i,i]+y[i,0]
        print(out)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]]
[  1  10 100]
[[  1  11 102]
 [  4  14 105]]
[[  1  11 102]
 [  4  14 105]
 [  7  17 108]]
[[  1]
 [ 10]
 [100]]
[  2  20 200]
[[  0  11 102]
 [  4  14 105]
 [  7  17 108]]
[[  0   0 102]
 [  4  14 105]
 [  7  17 108]]
[[  0   0   0]
 [  4  14 105]
 [  7  17 108]]
[[  0   0   0]
 [  7  14 105]
 [  7  17 108]]
[[  0   0   0]
 [  7   7 105]
 [  7  17 108]]
[[  0   0   0]
 [  7   7   7]
 [  7  17 108]]


IndexError: index 2 is out of bounds for axis 0 with size 2