In [9]:
## I/O with numpy
## As part of programming requirements we need to store data permanently for futuer purposes
## Files are a  very common permanent area to store out data
## Types of files 1) Binary files- Used to store binary data like images video files audio files etc
## 2) Text files-Used to store character data (.txt and .csv)
## To store and retrieve of numpy array in binary format save() and load() are used it stores with extension .npy
## Example below
import numpy as np
a= np.arange(0,100,10)
print(a)
np.save('kariuki',a)
print(a)

import numpy as np 
b= np.load('kariuki.npy')
print(b)
 

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]


In [16]:
## storage abd retrieve of data in text file we use savetxt()and loadtxt() functions

a=np.arange(1,20)
a
np.savetxt ('hum.txt',a)

b=np.loadtxt('hum.txt')
print(b)
print(type(b))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19.]
<class 'numpy.ndarray'>


In [21]:
## To store and retrieve data in csv file format is done wit savetxt() and load() with delimiter parameters
b
np.savetxt('jecinta.csv',b,delimiter=',')

c=np.loadtxt('jecinta.csv')
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

In [48]:
## Binary files
## create a 1D array
## Remember to load the file you have to use .npy extension
d=np.array([11,12,13,14,15])
d
np.save('njeri',d)
e=np.load('njeri.npy')
type (e)
## Remember always to save in a csv file you have to always pass the delimiter=,
e=np.array([11,12,13,24,25,26])
np.savetxt('wanjiku.csv',e,delimiter=',')
f=np.loadtxt("wanjiku.csv")
print(type(f))


<class 'numpy.ndarray'>


In [70]:
## sprinting line into columns
##genfromtxt runs two main loops. 
## The first loop converts each line of the file in a sequence of strings. 
##The second loop converts each string to the appropriate data type
from io import StringIO
hum=u"1, 2, 3\n4, 5, 6"
print(type(hum))
hum
np.genfromtxt(StringIO(hum),delimiter=",")

<class 'str'>


array([[1., 2., 3.],
       [4., 5., 6.]])

In [62]:
>>> data = u"""#
... # Skip me !
... # Skip me too !
... 1, 2
... 3, 4
... 5, 6 #This is the third line of the data
... 7, 8
... # And here comes the last line
... 9, 0
... """
>>> np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [78]:
from io import StringIO
data=u"\n".join(str(i) for i in range(10))
print(type(data))
data
## output will be like this'0\n1\n2\n3\n4\n5\n6\n7\n8\n9'
np.genfromtxt(StringIO(data),)





<class 'str'>


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])