In [12]:
## 2D array getting a specific element.You create a 1D array inside the other 1D array
import numpy as np
b=np.array ([[[1,2],[5,6]],[[4,3],[6,5]]])
print(b)
## Getting a specific element from the array
b[0] ## This will print the first matrix
b[0,0] ## This will print the first matrix the first row
b[0,0,0] ## This will print the first matrix the first row and the first element


[[[1 2]
  [5 6]]

 [[4 3]
  [6 5]]]


1

In [ ]:
## The identity matrix
b=np.identity(5)
print(b)
## linalg means linear algebra
np.linalg.det(b)

##Determinant
## Trace
## Singular vector decomposition
## Eigen Values
## Inverse 
## find them on (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

### Statistics


stat= np.array([[1,2,3],[4,5,6]])
stat
np.mean(stat)
np.min(stat)## The minimum value
np.max(stat) ## The maximum value
np.min (stat,axis=1) ## The min of the first row and the min of the second row
np.sum(stat)


## Reorganizing Arrays

before = np.array([[1,2,3,4],[4,5,6,8]])
after = before.reshape((8,1))
after


## Vertically Stacking Vectors


v1= np.array([1,2,3,4])
v2=np.array([5,6,7,8])

v3=np.vstack([v1,v2])
v4=np.vstack([v1,v2,v3])
print(v3)
print(v4)
v4.ndim

## Horizontal Stack

In [48]:
a=np.zeros([2,4]) ## 2 by 4 matrix of zeros
b=np.ones([2,2])
b
c=np.hstack([a,b])
b
c

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

## Miscellaneous

### Load Data from file

In [65]:
hum=np.genfromtxt('load.txt',delimiter=',')
hum
hum2=hum.astype('int32')
hum2
np.mean(hum2)
np.max(hum)
np.min(hum)
hum[0]
hum[10]
hum


array([  1.,  13.,  21.,  11., 196.,  75.,   4.,  56.,  78.,  99.,  34.,
         6.,   7.,   8.,   9.,  23.,   5.,   6.,   7.,  97.,   2.,   2.,
         4.,   4., 677.,   8.,   6.,  54.,  33.,   2.,   2., 345.,   6.,
         6.,   7.,  34.,   5.,   4.,   3.,   2.,   1.,   3.,   4.,   5.,
         6.,   7.,   8.,   9.,   0.,   5.,   3.,   2.,   2.,   4.,   5.,
         6.,   7.,   8.,   8.,   9.,   9.,   9.])

## Boolean masking and Advanced Indexing

In [79]:
hum>10
hum[hum>10] ## It prints out the data where it is greater than 10 only
## You can index with a list in Numpy
kariuki=np.array([1,2,3,4,5,6,7,8,9])
kariuki[[1,2,8]]
np.any(hum2>50 )## The output will be true since there is a value >50 in the data hum
np.any(hum2 > 50, axis=0)
hum[((hum>50)&(hum<100))]

array([75., 56., 78., 99., 97., 54.])

In [81]:
help?

In [ ]:
hum>10
hum[hum>10] ## It prints out the data where it is greater than 10 only
## You can index with a list in Numpy
kariuki=np.array([1,2,3,4,5,6,7,8,9])
kariuki[[1,2,8]]
np.any(hum2>50 )## The output will be true since there is a value >50 in the data hum
np.any(hum2 > 50, axis=0)
hum[((hum>50)&(hum<100))]